[build]
  command = "npm run build"
  publish="/Users/kenyounot/Documents/portfolio-site/portfolio/build"
  base = "/Users/kenyounot/Documents/portfolio-site/portfolio"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200